name: example-actions
on: [push]

jobs: 
  compile-java:
    name: Compile Java example
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '18'
      - name: Compile Java Example
        run: | 
          javac --release 18 --enable-preview -g \
          -classpath out -sourcepath java -d out ./java/*java
      - name: Test Java Example
        run: java --enable-preview -cp out VehicleFactory

  compile-kotlin:
    name: Compile Kotlin example
    needs: compile-java
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.10
      - name: Compile Kotlin Example
        run: | 
          kotlinc ./kotlin/*.kt -include-runtime \
          -d ./out/vehicle_factory.jar
      - name: Test Kotlin Example
        run: kotlin -classpath ./out/vehicle_factory.jar KVehicleFactoryKt

  compile-scala:
    name: Compile Scala example
    needs: compile-kotlin
    runs-ons: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Scala
        uses:  olafurpg/setup-scala@v11
        with:
          version: 2.13.8
      - name: Compile Scala Example
        run: scalac -d out ./scala/*.scala
      - name: Test Scala Example
        run: scala -cp out SVehicleFactory
